name: hellobella
favicon: null
layout_spectrum: 0.2323916843160987
typography_spectrum: 0.6308657736517489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7581583862192929
  lightness: 0.8178329691290855
  saturation: 0.3334050083067268
  rhythmicContrast: 0.5292119742371142
purpose: []
